apiVersion: v1
kind: Service
metadata:
  name: skore-back-service
  namespace: sk-team-05
spec:
  selector:
    app: skore-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  