apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-ai-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-ai
  template:
    metadata:
      labels:
        app: skore-ai
    spec:
      containers:
        - name: skore-ai
          image: idealhyun2/leadme5-ai@sha256:309d139faaefdf53e39dcf46dc277f4658d22b82e9d8469a95cb5613f2d3c710
          ports:
            - containerPort: 8000
