apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-ai-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-ai
  template:
    metadata:
      labels:
        app: skore-ai
    spec:
      containers:
        - name: skore-ai
          image: idealhyun2/leadme5-ai@sha256:a1753acd1ba5ad824d01088a88b984659241b00b85eccc5d73a87aa8a5b9e773
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: DB_URL
