apiVersion: v1
kind: Service
metadata:
  name: skore-ai-service
  namespace: sk-team-05
spec:
  selector:
    app: skore-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
  