apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-front-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-front
  template:
    metadata:
      labels:
        app: skore-front
    spec:
      containers:
        - name: skore-front
          image: idealhyun2/leadme5-front@sha256:e0a3f48342684c107069aebd440b71ae6873ab9cb6444a64776254137bf00316
          ports:
            - containerPort: 80
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-front-secret
                  key: JWT_SECRET
