apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-front-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-front
  template:
    metadata:
      labels:
        app: skore-front
    spec:
      containers:
        - name: skore-front
          image: idealhyun2/leadme5-front@sha256:26311257bbcb268874e374634c38de1ecc0dd28bd7a915a7aae7ee641c35dc5e
          ports:
            - containerPort: 80
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-front-secret
                  key: JWT_SECRET
