apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-front-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-front
  template:
    metadata:
      labels:
        app: skore-front
    spec:
      containers:
        - name: skore-front
          image: idealhyun2/leadme5-front@sha256:da49ade1d65cc32b7574fb7de63ef0999f8f1d04aeba6203485284fd2c946785
          ports:
            - containerPort: 80
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-front-secret
                  key: NEXT_PUBLIC_API_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-front-secret
                  key: JWT_SECRET
