apiVersion: apps/v1
kind: Deployment
metadata:
  name: skore-front-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skore-front
  template:
    metadata:
      labels:
        app: skore-front
    spec:
      containers:
        - name: skore-front
          image: idealhyun2/leadme5-front@sha256:df98f40076bb1182d627f107666443c5d78307091fa49a801d0b4bbce575d22f
          ports:
            - containerPort: 80
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-front-secret
                  key: JWT_SECRET
