apiVersion: v1
kind: Service
metadata:
  name: skore-front-service
  namespace: sk-team-05
spec:
  selector:
    app: skore-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  